### PR TITLE
feat: replacing bytes.Buffer instances used only to generate strings with strings.Builder. 

### PR DESCRIPTION
**Pull request by ellisonleao**
Ref #223

### CODE REVIEW

**Comment by ellisonleao** [comment]
done @maxatome

**Comment by maxatome** [comment]
My bad, by *renaming `SliceToBuffer` to `SliceToString`* I also meant changing the signature from using `*bytes.Buffer` to `*string.Builder`. Sorry.

**Comment by ellisonleao** [comment]
@maxatome any suggestions on how to handle `buf.Truncate()` and `buf.Bytes()`,  since they don't exist in `strings.Builder`?

**Comment by maxatome** [comment]
- `buf.Bytes()` is used by `bytes.LastIndexByte` so it can be replaced by `buf.String()` and `strings.LastIndexByte`;
- `buf.Truncate()` call can be avoided by reworking the preceding loop:
  ```go
  buf.WriteString(IndentString(ToString(items[0]), prefix))
  for _, item := range items[1:] {
    buf.WriteString(",\n")
    buf.WriteString(prefix)
    buf.WriteString(IndentString(ToString(item), prefix))
  }
  ```
  (not tested :) )

**Comment by ellisonleao** [comment]
done @maxatome

**Review by maxatome — APPROVED** [review]

**Comment by maxatome** [comment]
Thanks a lot @ellisonleao ! 😉 And welcome as go-testdeep contributor.

**Pull request merged**
